### ISSUE TITLE
Task Tracker (Pomodoro-App)

### ISSUE THREAD

**Issue by Kh4lil** [Kh4lil/Pomodoro-App#1]
- [x] Finish design in Figma
- [x] Upload initial files
- [x] HTML
- [x] CSS
- [x] Responsiveness
- [x] Start JavaScript
- [x] Add alert at the end of the timer
- [x] Add trophies at the end of timer. 
- [ ] Add FAQ. 
- [ ] Add About Me redirect. 
- [ ] Add Settings. 
- [ ] embed Study playlist.
- [ ] replace setInterval()
- [ ] add login
