### ISSUE TITLE
Bug tracker

### ISSUE THREAD

**Issue by Kh4lil** [Kh4lil/Pomodoro-App#2]
These are the bugs found during the testing phase: 

- [x] Clicking multiple times on the Start button will speedup the clock. 
- [x] The timer is not centered when it shows <02:00 minutes left
- [x] 'undefined' at the end of timer. 
- [x] Tree images not loading correctly on the github pages.
